AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "*.gemspec"
    - "gemfiles/*"
    - gems/**/*
    - node_modules/**/*
    - vendor/bundle/**/*
    - Rakefile
    - Gemfile

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false  
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/WordArray:
  Enabled: false
